version: "3.8"

services:
  postgres:
    image: postgres:13-alpine
    env_file: 
      - .env
    volumes:
      - database-data: /var/lib/postgresql/data/

  bot:
    build: .
    environment: 
      - PRODUCTION=True
    command: python bot.py
    volumes:
      - bot: /bot
    depends_on: 
      - db

volumes:
  database-data:
  bot:
    